### ISSUE TITLE
Publishing on crates.io

### ISSUE THREAD

**Issue by IvanUkhov** [strawlab/accelerate-src#6]
Hi @astraw, could you please add me to the owners list on crates.io so that I’m able to publish this crate? Thank you!

**Comment by astraw** [comment]
Via the crates.io system I should have sent you a couple email invites to become an owner. Did you get them? I don't see you as an owner yet, so I guess you haven't accepted as of now.

**Comment by IvanUkhov** [comment]
I haven’t received any notifications from crates.io, and I haven’t found anything in the spam folder. Could you please try it via the command line?

```bash
git clone git@github.com:blas-lapack-rs/accelerate-src.git
cd accelerate-src
cargo owner --add IvanUkhov
```

**Comment by astraw** [comment]
I ran `cargo owner --add IvanUkhov` from the command line, which then printed `Owner user IvanUkhov has been invited to be an owner of crate accelerate-src`. So, please let me know if it worked this way.

**Comment by IvanUkhov** [comment]
Perfect! Thanks a lot!
